version: '3.8'

services:
  bot:
    image: bot-api:0.1.0-SNAPSHOT
    container_name: bot-service
    ports:
      - "8081:8081"
    expose:
      - 8081
    depends_on:
      - scrapper

  scrapper:
    image: scrapper-api:0.1.0-SNAPSHOT
    container_name: scrapper-service
    ports:
      - "8080:8080"
    expose:
      - 8080
