version: '3.8'

networks:
  link-scrapper-network:

services:
  bot:
    image: bot-api:0.1.0-SNAPSHOT
    container_name: bot-service
    ports:
      - "8081:8081"
    expose:
      - 8081
    env_file:
      - ../bot/src/main/resources/.env
    depends_on:
      - scrapper
    networks:
      - link-scrapper-network

  scrapper:
    image: scrapper-api:0.1.0-SNAPSHOT
    container_name: scrapper-service
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - link-scrapper-network
