name: Scala CI

on:
  push:
  pull_request:

jobs:
  build_and_test:
    runs-on: edu-self-hosted
    container:
      image: maven:3-eclipse-temurin-24
    timeout-minutes: 10
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: sbt
      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1
      - name: Check formatting
        run: sbt scalafmtCheckAll
      - name: Run tests
        run: sbt test
