name: Scala CI

on:
  push:
  pull_request:

jobs:
  build_and_test:
    runs-on: edu-self-hosted
    container:
      image: sbtscala/scala-sbt:eclipse-temurin-21.0.6_7_1.10.10_3.3.5
    timeout-minutes: 10
    name: Build and Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check formatting
        run: sbt scalafmtCheckAll
      - name: Run tests
        run: sbt test
